name: Ci/CD Pipeline

on: 
  push:
    branches: [ "main" ]

jobs:
  Setup:
    name: Setup go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: actions/checkout@v4
      - name: Run Unit Tests
        run: go test
