name: Ci/CD Pipeline

on: 
  push:
    branches: [ "main" ]

jobs:
  Setup:
    name: Setup and test go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: actions/checkout@v4
      - name: Run Unit Tests
        run: go test

  Build:
    name: Build application in container
    runs-on: ubuntu-latest
    needs: Setup

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3.6.1
      - run: docker build -t golang-pipeline:dev .
      - run: docker image ls
      - run: docker run --rm golang-pipeline:dev
